import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "ZoneDoctor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
      <div className="md:px-20">
        <Header />
        {children}
      </div>
      </body>
    </html>
  );
}
